# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 10c178950196de25e25ad4087d7a46dbb9ab068d75386e543d3576c86de63df86593529a5d0d16d00816af649674ff87d304473dc6e395b8d92d3fb1ec9275d2

test:
  secret_key_base: 656d61967cc701fd964e7e4dfd61e7df902904ea95aade3d9a99771da17a48f515d49e11d9f00bf3f6d0fbe9ebc8f09d8185d0363a45c7d536fb326774e8a3c8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
